# Generated by Django 2.2.6 on 2019-11-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(max_length=120)),
                ('fecha_nacimiento', models.DateField()),
                ('foto_perfil', models.ImageField(default=None, upload_to='photos')),
                ('celular', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
