# Generated by Django 2.2.6 on 2019-11-26 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('coment_id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.User')),
            ],
        ),
    ]
