# Generated by Django 2.2.6 on 2019-11-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('noti_id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.User')),
            ],
        ),
    ]
