# Generated by Django 2.2.6 on 2019-11-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_auto_20191126_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguidores',
            old_name='seguido_id',
            new_name='seguido',
        ),
        migrations.RenameField(
            model_name='seguidores',
            old_name='seguidor_id',
            new_name='seguidor',
        ),
    ]
