# Generated by Django 2.2.6 on 2020-02-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0011_remove_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
