# Generated by Django 2.2.6 on 2020-03-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0012_auto_20200229_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='etiquetas',
        ),
        migrations.RemoveField(
            model_name='seguidores',
            name='aceptado',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.CharField(max_length=280),
        ),
        migrations.DeleteModel(
            name='Notificaciones',
        ),
    ]
